//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO_HOSPITALARIO
    {
        public int IdCentroHospitalario { get; set; }
        public string NombreHospital { get; set; }
        public string Director { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> IdLugar { get; set; }
        public Nullable<int> Capacidad { get; set; }
    
        public virtual LUGAR LUGAR { get; set; }
    }
}
