//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO
    {
        public int IdContacto { get; set; }
        public string NombreContacto { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public string Apellidos { get; set; }
        public string NumIdentificacionContacto { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> IdLugar { get; set; }
        public string Nacionalidad { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdPatologia { get; set; }
    
        public virtual LUGAR LUGAR { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual PATOLOGIA PATOLOGIA { get; set; }
    }
}
