//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoTECEntities : DbContext
    {
        public CoTECEntities()
            : base("name=CoTECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CENTRO_HOSPITALARIO> CENTRO_HOSPITALARIO { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<LUGAR> LUGAR { get; set; }
        public virtual DbSet<MEDICAMENTO> MEDICAMENTO { get; set; }
        public virtual DbSet<MEDIDA_SANITARIA> MEDIDA_SANITARIA { get; set; }
        public virtual DbSet<PATOLOGIA> PATOLOGIA { get; set; }
        public virtual DbSet<MEDIDAS_PAIS> MEDIDAS_PAIS { get; set; }
        public virtual DbSet<REPORTES_ESTADOS> REPORTES_ESTADOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<REPORTES_CASOS> REPORTES_CASOS { get; set; }
        public virtual DbSet<CONTACTO> CONTACTO { get; set; }
        public virtual DbSet<ESTADO_PACIENTE> ESTADO_PACIENTE { get; set; }
        public virtual DbSet<PACIENTE> PACIENTE { get; set; }
    }
}
