//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.CONTACTO = new HashSet<CONTACTO>();
        }
    
        public string NombrePaciente { get; set; }
        public string Apellidos { get; set; }
        public int IdPaciente { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> IdLugar { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string IdContactos { get; set; }
        public string Email { get; set; }
        public string Internado { get; set; }
        public Nullable<int> IdPatologia { get; set; }
        public Nullable<int> IdMedicamento { get; set; }
        public string NumIdentificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACTO> CONTACTO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ESTADO_PACIENTE ESTADO_PACIENTE { get; set; }
        public virtual LUGAR LUGAR { get; set; }
        public virtual MEDICAMENTO MEDICAMENTO { get; set; }
        public virtual PATOLOGIA PATOLOGIA { get; set; }
    }
}
