//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES_CASOS
    {
        public Nullable<int> IdLugar { get; set; }
        public Nullable<int> CasosNuevos { get; set; }
        public Nullable<int> Muertes { get; set; }
        public int IdReportesCasos { get; set; }
    
        public virtual LUGAR LUGAR { get; set; }
    }
}
